.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH hanko 1  "hanko " 
.SH NAME
hanko \- Keeps your Git allowed signers file up to date with signing keys configured on software development platforms like GitHub and GitLab.
.SH SYNOPSIS
\fBhanko\fR [\fB\-v\fR|\fB\-\-verbose\fR]... [\fB\-c\fR|\fB\-\-config\fR] [\fB\-\-file\fR] [\fB\-h\fR|\fB\-\-help\fR] <\fIsubcommands\fR>
.SH DESCRIPTION
Keeps your Git allowed signers file up to date with signing keys configured on software development platforms like GitHub and GitLab.
.SH OPTIONS
.TP
\fB\-v\fR, \fB\-\-verbose\fR
Use verbose output
.TP
\fB\-c\fR, \fB\-\-config\fR=\fIPATH\fR [default: ~/.config/hanko/config.toml]
The configuration file
.RS
May also be specified with the \fBHANKO_CONFIG\fR environment variable. 
.RE
.TP
\fB\-\-file\fR=\fIPATH\fR
The allowed signers file
.RS
May also be specified with the \fBHANKO_ALLOWED_SIGNERS\fR environment variable. 
.RE
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.SH SUBCOMMANDS
.TP
hanko\-update(1)
Update the allowed signers file
.TP
hanko\-signer(1)
Manage allowed signers
