---
name: Cargo Deny

on:
  pull_request:
    paths:
      - "**/Cargo.lock"
      - "**/Cargo.toml"
      - "deny.toml"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  cargo-deny:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8
      - uses: EmbarkStudios/cargo-deny-action@30f817c6f72275c6d54dc744fbca09ebc958599f
        with:
          command: check bans licenses sources advisories
